spring:
  datasource:
#    url: jdbc:h2:tcp://localhost/~/jpashop;MVCC=TRUE
    url: jdbc:h2:tcp://localhost/~/jpashop;
    username: sa
    password:
    driver-class-name: org.h2.Driver


  jpa:
    hibernate:
      ddl-auto: none # ddl을 drop하지 않기 때문에 한번 저장된 데이터는 유지 된다
    properties:
      hibernate:
        show_sql: true # System.out.println()에 출력 (시스템 환경에서는 모두 로그로 출력하는 습관 필요)
        format_sql: true

logging:
  level:
    org.hibernate.SQL: debug #JPA or Hibernate가 생성하는 sql을 볼 수 있다.
    org.hibernate.type: trace # 쿼리 파라미터 로그가 ?로만 나오던 것을 어떤값이 들어있는지 로그로 출력해주는 기능



